#!/usr/bin/env python3

import argparse
from datetime import date

parser = argparse.ArgumentParser(
    description=
    'Adds a commented header section to the specified (System)Verilog file.')
parser.add_argument('filename', type=str, help='File to vheader.')
parser.add_argument('--author',
                    type=str,
                    help='Author name.',
                    default="Aditya V. Nebhrajani")
args = parser.parse_args()

header = [
    '//' + '-' * 80 + '\n',
    ' '.join(['//', '(c)', args.author,
              str(date.today().year) + '\n']), '// ' + 'Description: \n',
    '// ' + 'Author: ' + args.author + '\n', '//' + '-' * 80 + '\n', '\n'
]

with open(args.filename, "r") as f:
    contents = f.readlines()

contents = header + contents

with open(args.filename, "w") as f:
    f.writelines(contents)
